### ISSUE TITLE
Note in R CMD CHECK because of encoding 

### ISSUE THREAD

**Issue by lbelzile** [r-fndv/mvPot#4]
When checking the package build on Windows, there is a note warning of the presence of non-ASCII characters. These are declared in the Roxygen tags (via `\enc{}{}` and a tag `#' @encoding UTF8`, but somehow `R CMD CHECK --as-cran` picks them up since they also are in the .R file.

> using session charset: ISO8859-1
> 
> No package encoding and non-ASCII characters in the following R files:
>   R/censored_likelihood_XS.R
>     26: #' @references Ribatet, M. (2013). Spatial extremes: max-stable processes at work. Journal de la \enc{Soci<c3><a9>t<c3><a9>}{Societe} \enc{Fran<c3><a7>aise}{Francaise} de Statistique, 154(2), 156-177.

I do not get the warning on my Unix system using _R-devel_.
A quick solution is to generate the .Rd file and to remove the tags. Any better idea?

**Comment by r-fndv** [comment]
Non-ASCII characters removed in last push request.
